# Generated by Django 5.0 on 2024-04-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.TextField(max_length=10)),
                ('address', models.TextField(max_length=255)),
                ('vendor_code', models.CharField(max_length=8)),
                ('on_time_delivery', models.FloatField(max_length=4)),
                ('quality_rating_avg', models.FloatField(max_length=4)),
                ('average_response_time', models.FloatField(max_length=4)),
                ('fulfillment_rate', models.FloatField(max_length=4)),
            ],
        ),
    ]
